ARG VERSION=v0.4.1

FROM openmmlab/lmdeploy:${VERSION}

#ENV PIP_INDEX_URL=https://mirrors.ustc.edu.cn/pypi/web/simple

RUN pip install --no-cache-dir prometheus_fastapi_instrumentator

ENV ENABLE_METRICS=1

ARG LMDEPLOY_PATH

COPY ./lmdeploy/serve/openai/api_server.py /tmp/api_server.py

# add custom api_server.py to lmdeploy package dynamically by copying it to the package directory
RUN mv /tmp/api_server.py $(pip show lmdeploy | grep Location | awk '{print $2}')/lmdeploy/serve/openai/api_server.py